#pragma once

#include <algorithm>
#include <assert.h>
#include <atomic>
#include <cstring>
#include <errno.h>
#include <fcntl.h>
#include <fstream>
#include <float.h>
#include <iostream>
#include <limits.h>
#include <list>
#include <map>
#include <math.h>
#include <set>
#include <signal.h>
#include <string>
#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <stdexcept>
#include <stdint.h>
#include <sstream>
#include <time.h>
#include <vector>
#include <sys/sem.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <ctype.h>
#include <byteswap.h>
#include <dirent.h>
#include <dlfcn.h>
#include <ifaddrs.h>
#include <inttypes.h>  
#include <netdb.h>
#include <pthread.h>
#include <semaphore.h>
#include <syslog.h>
#include <unistd.h>
#include <linux/version.h>
#include <arpa/inet.h>
#include <sys/mman.h>
#include <sys/time.h>
#include <sys/socket.h>
#include <sys/epoll.h>
#include <sys/wait.h>
#include <sys/resource.h>
#include <netdb.h>
#include <net/if.h>
#include <netinet/in.h>